In [1]:
import json # will be needed for saving preprocessing details
import numpy as np # for data manipulation
import pandas as pd # for data manipulation
from sklearn.model_selection import train_test_split # will be used for data split
from sklearn.preprocessing import LabelEncoder # for preprocessing
from sklearn.ensemble import RandomForestClassifier # for training the algorithm
from sklearn.ensemble import ExtraTreesClassifier # for training the algorithm
import joblib # for saving algorithm and preprocessing objects

In [59]:
df = pd.read_csv('https://raw.githubusercontent.com/DebohOlate/my_ml_service/master/datosModificados.csv', sep=';', low_memory=False)

In [60]:
print(df)

       Unnamed: 0         Map              Team  InternalTeamId  MatchId  \
0             600  de_inferno         Terrorist               1        4
1             601  de_inferno         Terrorist               1        4
2             602  de_inferno         Terrorist               1        4
3             603  de_inferno         Terrorist               1        4
4             604  de_inferno         Terrorist               1        4
...           ...         ...               ...             ...      ...
79152      123775   de_mirage  CounterTerrorist               2      511
79153      123776   de_mirage  CounterTerrorist               2      511
79154      123777   de_mirage  CounterTerrorist               2      511
79155      123778   de_mirage  CounterTerrorist               2      511
79156      123779   de_mirage  CounterTerrorist               2      511

       RoundId   SteamId  RoundWinner  MatchWinner  Survived  ...  \
0            1  7,66E+16        False         True     False  ...
1            1  7,66E+16        False         True     False  ...
2            1  7,66E+16        False         True     False  ...
3            1  7,66E+16        False         True     False  ...
4            1  7,66E+16        False         True      True  ...
...        ...       ...          ...          ...       ...  ...
79152        5  7,66E+16        False        False     False  ...
79153        5  7,66E+16        False        False     False  ...
79154        5  7,66E+16        False        False     False  ...
79155        5  7,66E+16        False        False     False  ...
79156        5  7,66E+16        False        False      True  ...

       RoundStartingEquipmentValue TeamStartingEquipmentValue MatchKills  \
0                              750                       4400          0
1                              800                       4400          0
2                             1000                       4400          0
3                              850                       4400          0
4                             1000                       4400          0
...                            ...                        ...        ...
79152                         5600                      27100          4
79153                         5500                      27100          8
79154                         4950                      27100          5
79155                         4950                      27100          1
79156                         6100                      27100          5

      MatchFlankKills MatchAssists MatchHeadshots        AvgMatchKillDist  \
0                   0            0              0   5.013.791.830.906.020
1                   0            0              0  20.880.758.729.744.000
2                   0            0              0   3.816.520.279.110.340
3                   0            0              0   2.897.545.030.908.390
4                   0            0              0   2.545.276.911.760.720
...               ...          ...            ...                     ...
79152               0            2              2   7.680.038.788.432.440
79153               5            1              3   6.922.626.056.397.950
79154               0            2              3  16.131.078.365.315.700
79155               0            1              0   9.845.751.993.727.740
79156               1            1              2   6.333.057.962.307.570

      MapId  MatchWinnerId  RoundWinnerId
0         0              1              0
1         0              1              0
2         0              1              0
3         0              1              0
4         0              1              0
...     ...            ...            ...
79152     3              0              0
79153     3              0              0
79154     3              0              0
79155     3              0              0
79156     3              0              0

[79157 rows x 40 columns]

In [61]:
# set input matrix and target column
X = df[['InternalTeamId', 'MapId']]
y = df['MatchWinner']
df.head()

,Unnamed: 0,Map,Team,InternalTeamId,MatchId,RoundId,SteamId,RoundWinner,MatchWinner,Survived,...,RoundStartingEquipmentValue,TeamStartingEquipmentValue,MatchKills,MatchFlankKills,MatchAssists,MatchHeadshots,AvgMatchKillDist,MapId,MatchWinnerId,RoundWinnerId
0,600,de_inferno,Terrorist,1,4,1,"7,66E+16",False,True,False,...,750,4400,0,0,0,0,5.013.791.830.906.020,0,1,0
1,601,de_inferno,Terrorist,1,4,1,"7,66E+16",False,True,False,...,800,4400,0,0,0,0,20.880.758.729.744.000,0,1,0
2,602,de_inferno,Terrorist,1,4,1,"7,66E+16",False,True,False,...,1000,4400,0,0,0,0,3.816.520.279.110.340,0,1,0
3,603,de_inferno,Terrorist,1,4,1,"7,66E+16",False,True,False,...,850,4400,0,0,0,0,2.897.545.030.908.390,0,1,0
4,604,de_inferno,Terrorist,1,4,1,"7,66E+16",False,True,True,...,1000,4400,0,0,0,0,2.545.276.911.760.720,0,1,0

In [62]:
# division de data entrenamiento/ prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1234)

In [63]:
# completar valores faltantes con el valor mas frecuente
train_mode = dict(X_train.mode().iloc[0])
X_train = X_train.fillna(train_mode)
print(train_mode)

{'InternalTeamId': 1, 'MapId': 0}

In [66]:
# convertir categoricos en numeros
encoders = {}
for column in ['InternalTeamId', 'MapId']:
    categorical_convert = LabelEncoder()
    X_train[column] = categorical_convert.fit_transform(X_train[column])
    encoders[column] = categorical_convert

# Entrenamiento de algoritmos

In [68]:
# Entrenando el algoritmo de Random Forest
rf = RandomForestClassifier(n_estimators = 100)
rf = rf.fit(X_train, y_train)

In [69]:
# Entrenando el algoritmo de Extra Trees
et = ExtraTreesClassifier(n_estimators = 100)
et = et.fit(X_train, y_train)

In [70]:
# guardar las viariables de procesamiento train_mode y encoders
joblib.dump(train_mode, "./train_mode.joblib", compress=True)
joblib.dump(encoders, "./encoders.joblib", compress=True)
joblib.dump(rf, "./random_forest.joblib", compress=True)
joblib.dump(et, "./extra_trees.joblib", compress=True)

['./extra_trees.joblib']

# Agregar Codigo Machine Learning